project:
  type: website
  output-dir: "a6ee114667f8de829f08570ecd63cfa18045cfee4"

website:
  title: "a6ee114667f8de829f08570ecd63cfa18045cfee4"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

