project:
  type: website
  output-dir: "a38a0578fb0f2342fa9ab4ca213cdfffe89063dd8"

website:
  title: "Chad Portal"
  navbar:
    left:
      - href: https://chadchae.github.io/portfolio_course
        text: Research Portfolio
      - href: https://chadchae.github.io/portfolio_working
        text: Course Portfolio

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

# editor: visual

