project:
  type: website
  output-dir: "a6ee114667f8de829f08570ecd63cfa18045cfee4"

website:
  title: "Chad Portal"
  navbar:
    left:
      - text: "Research"
        menu:
          - text: Working Research Portfolio
            href: https://chadchae.github.io/portfolio_working
          - text: Completed Research Project Archieve
            href: TBA 
      - text: "Course Development"
        menu:
          - text: Current Teaching Courses Portfolio
            href: https://chadchae.github.io/portfolio_course
          - text: Completed Course Development Portfolio
            href: TBA 
      - text: "Lecture Series"
        menu:
          - text: TBA
            href: TBA 
      - text: "Workshop"
        menu:
          - text: TBA 
            href: TBA
      - text: "Presentation & Talk"
        menu:
          - text: TBA 
            href: TBA 
      - text: "Development"
        menu:
          - text: TBA 
            href: TBA 
      - text: "ETC"
        menu:
          - text: TBA 
            href: TBA 

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

# editor: visual

